package enc

const (
	PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3d3/Eodx/pdPkuYJ5Jjl
MdzzXp6mywDLX9rUycilWPYwkefSQ2TDW2y0rrDTWHY+S6ToDKcdOdeZoBuA0wxy
eFGnqkO77xFE848/JQZ613qPQHE/bq7f/fZNLctvjuZ5ADJ17PHygc4YX6GaczKb
HytIfBtkhSItC1faB5gl7psNFa7vSLHEQMeYX1nZI/S90DxDfk4CqY9lBOOzxEr6
ZjYbyfcQSQmh2Wfstz5ZIzpJcRnKtkrp/bX1OkBL3WPT+JESG/Sm/d0FRcvmwXUU
TerL6q+yskKrFYUyTJvW7rhnyDLlcfEkRQo/K9GsJEKX/H8QE3qeeDOSqiRgfq57
fQIDAQAB
-----END PUBLIC KEY-----`

	PAYMENT_TYPE = "adyen_cards"
)
